#50: Remove the "ANSIBLE_ARGS" environment variable

diff --git a/bash/cikit b/bash/cikit
--- a/bash/cikit
+++ b/bash/cikit
@@ -3,6 +3,7 @@
 # The internal version of CIKit.
 VERSION="0.0.1"
 COMMAND="ansible-playbook"
+LOCALHOST=false
 # List of parameters for "ansible-playbook" command.
 PARAMS=""
 # JSON formatted "--extra-vars" options.
@@ -48,30 +49,14 @@ extra_var()
   # Remove all data after "=" symbol.
   local name=${1%=*}
   local value=${1#*=}
-  local SKIP=false
 
   # Remove leading "--".
   name=${name#--}
   value=${value#--}
 
-  # List of allowed variables for passing as parameters for "ansible-playbook".
-  for ansible_reserved_name in limit tags list-tags; do
-    if [ "${name}" == "${ansible_reserved_name}" ]; then
-      PARAMS+=" --${name}"
-      # Don't allow passing the reserved by Ansible parameter as a variable.
-      SKIP=true
-
-      # Since we're not formatting parameters as JSON then we aren't interested
-      # in a value for the parameter. It simply can be valueless.
-      if [ "${name}" != "${value}" ]; then
-        PARAMS+="=${value}"
-      fi
-
-      break
-    fi
-  done
-
-  if ! ${SKIP}; then
+  if [ "limit" == "${name}" ]; then
+    PARAMS+=" --${name}=${value}"
+  else
     if [[ "${name}" == "${value}" || "" == "${value}" ]]; then
       value="true"
     fi
@@ -169,102 +154,119 @@ if [ $? -gt 0 ]; then
   error 12 "The \"$1\" command is not available."
 fi
 
-if \grep -qo "^# requires-project-root$" "${PLAYBOOK}" && ! is_project_root "${TARGET_DIR}"; then
-  error 34 "Execution of the \"$1\" is available only within the CIKit-project directory."
+if \grep -qo "^# requires-project-root$" "${PLAYBOOK}"; then
+  if ! is_project_root "${TARGET_DIR}"; then
+    error 34 "Execution of the \"$1\" is available only within the CIKit-project directory."
+  fi
+else
+  # When the playbook is not required to be run in the root
+  # directory of the project we can simply execute it locally.
+  LOCALHOST=true
 fi
 
-# Check whether playbook has declared mandatory options via "# ro:OPTION" annotation.
-# If one of the required options is missing, then continuation will be stopped.
-while IFS= read -r mandatory_option; do
-  required_option_passed=false
+if [ -n "${CIKIT_VERBOSE}" ]; then
+  PARAMS+=" -vv"
+fi
 
-  for option in $(IFS="--" \echo "$@"); do
-    if [[ "${option}" =~ --${mandatory_option}=.{2,} ]]; then
-      required_option_passed=true
-      break
+if [ -n "${CIKIT_LIST_TAGS}" ]; then
+  PARAMS+=" --list-tags"
+  LOCALHOST=true
+else
+  # Check whether playbook has declared mandatory options via "# ro:OPTION" annotation.
+  # If one of the required options is missing, then continuation will be stopped.
+  while IFS= read -r mandatory_option; do
+    required_option_passed=false
+
+    for option in $(IFS="--" \echo "$@"); do
+      if [[ "${option}" =~ --${mandatory_option}=.{2,} ]]; then
+        required_option_passed=true
+        break
+      fi
+    done
+
+    if ! ${required_option_passed}; then
+      error 44 "The \"--${mandatory_option}\" option is required for the \"${1}\" command and currently missing or has a value less than 2 symbols."
     fi
-  done
+  done < <(\awk -F ':' '/^# ro:.+?$/ {print $2}' "${PLAYBOOK}")
 
-  if ! ${required_option_passed}; then
-    error 44 "The \"--${mandatory_option}\" option is required for the \"${1}\" command and currently missing or has a value less than 2 symbols."
-  fi
-done < <(\awk -F ':' '/^# ro:.+?$/ {print $2}' "${PLAYBOOK}")
+  # See "provisioner.rb" to get know when it creates.
+  ENV_CONFIG="${CIKIT_DIR}/environment.yml"
 
-# See "provisioner.rb" to get know when it creates.
-ENV_CONFIG="${CIKIT_DIR}/environment.yml"
+  if [ -f "${ENV_CONFIG}" ]; then
+    # It's interesting trick with detecting Python interpreter. Sometimes it may differ. Especially
+    # on MacOS, when Ansible installed via Homebrew. For instance, "which python" returns
+    # the "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7",
+    # but this particular setup may not have necessary packages for full Ansible operability. Since
+    # Ansible - is a Python scripts, they must have a shadebag line with path to interpreter they
+    # should run by. Grab it and try!
+    # Given:
+    #   $(realpath $(which python)) -c 'import yaml'
+    # Ends by:
+    #   Traceback (most recent call last):
+    #     File "<string>", line 1, in <module>
+    #   ImportError: No module named yaml
+    # But:
+    #   $(cat $(which "ansible-playbook") | head -n1 | tr -d '#!') -c 'import yaml'
+    # Just works.
+    PYTHON_INTERPRETER=$(\head -n1 < "$(\which "${COMMAND}")" | \tr -d '#!')
 
-if [ -f "${ENV_CONFIG}" ]; then
-  # It's interesting trick with detecting Python interpreter. Sometimes it may differ. Especially
-  # on MacOS, when Ansible installed via Homebrew. For instance, "which python" returns
-  # the "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7",
-  # but this particular setup may not have necessary packages for full Ansible operability. Since
-  # Ansible - is a Python scripts, they must have a shadebag line with path to interpreter they
-  # should run by. Grab it and try!
-  # Given:
-  #   $(realpath $(which python)) -c 'import yaml'
-  # Ends by:
-  #   Traceback (most recent call last):
-  #     File "<string>", line 1, in <module>
-  #   ImportError: No module named yaml
-  # But:
-  #   $(cat $(which "ansible-playbook") | head -n1 | tr -d '#!') -c 'import yaml'
-  # Just works.
-  PYTHON_INTERPRETER=$(\head -n1 < "$(\which "${COMMAND}")" | \tr -d '#!')
-
-  if [ -x "${PYTHON_INTERPRETER}" ]; then
-    VARS=$("${PYTHON_INTERPRETER}" -c "exec(\"import yaml,json\nprint json.dumps(yaml.load(open('${ENV_CONFIG}')))\")")
-    VARS="${VARS##\{}"
-    VARS="${VARS%%\}},"
-  else
-    warn "WARNING: Cannot read environment configuration from \"${ENV_CONFIG}\". Looks like Python setup cannot provide Ansible operability."
-  fi
-fi
-
-# If the "EXTRA_VARS" passed as environment variable then parse it first to
-# not allow overwrite explicitly passed options.
-if [ -n "${EXTRA_VARS}" ]; then
-  for var in $(IFS="--" \echo "${EXTRA_VARS}"); do
-    extra_var "${var}"
-  done
-fi
-
-# The first argument always treated as a CIKit command. All others are parameters.
-for ((i = 2; i <= $#; i++)); do
-  extra_var "${!i}"
-done
-
-# Remove last comma.
-VARS=${VARS%%,}
-
-# Pass any extra arguments for "ansible-playbook". Most useful
-# case: "ANSIBLE_ARGS=-vvvv cikit reinstall"
-if [ -n "${ANSIBLE_ARGS}" ]; then
-  PARAMS+=" ${ANSIBLE_ARGS}"
-fi
-
-if [ -z "${ANSIBLE_INVENTORY}" ]; then
-  # Attach the inventory only when "-i localhost," is not specified.
-  if [[ ! "${PARAMS}" =~ localhost, ]]; then
-    INVENTORY=$(match_file "${CIKIT_DIR}/inventory")
-
-    if [ $? -eq 0 ]; then
-      # Move "inventory" into user's home directory because it is not mounted file
-      # system and can be affected via Linux commands (chmod, chown) under Windows.
-      \cp "${INVENTORY}" ~/.cikit-inventory
-      \chmod a-x ~/.cikit-inventory
-      PARAMS+=" -i ~/.cikit-inventory"
+    if [ -x "${PYTHON_INTERPRETER}" ]; then
+      VARS=$("${PYTHON_INTERPRETER}" -c "exec(\"import yaml,json\nprint json.dumps(yaml.load(open('${ENV_CONFIG}')))\")")
+      VARS="${VARS##\{}"
+      VARS="${VARS%%\}},"
+    else
+      warn "WARNING: Cannot read environment configuration from \"${ENV_CONFIG}\". Looks like Python setup cannot provide Ansible operability."
     fi
   fi
-# The "uname -o" cannot be used due to "-o" option is not supported on OS X.
-elif [[ "$(\uname -s)" =~ "CYGWIN" ]]; then
-  ANSIBLE_INVENTORY=$(\cygpath "${ANSIBLE_INVENTORY}")
+
+  if [ -n "${CIKIT_TAGS}" ]; then
+    PARAMS+=" --tags='${CIKIT_TAGS}'"
+  fi
+
+  # If the "EXTRA_VARS" passed as environment variable then parse it first to
+  # not allow overwrite explicitly passed options.
+  if [ -n "${EXTRA_VARS}" ]; then
+    for var in $(IFS="--" \echo "${EXTRA_VARS}"); do
+      extra_var "${var}"
+    done
+  fi
+
+  # The first argument always treated as a CIKit command. All others are parameters.
+  for ((i = 2; i <= $#; i++)); do
+    extra_var "${!i}"
+  done
+
+  # Remove last comma.
+  VARS=${VARS%%,}
+
+  # Non-documented feature needed for Vagrant purposes only.
+  if [ -z "${ANSIBLE_INVENTORY}" ]; then
+    if ! ${LOCALHOST}; then
+      INVENTORY=$(match_file "${CIKIT_DIR}/inventory")
+
+      if [ $? -eq 0 ]; then
+        # Move "inventory" into user's home directory because it is not mounted file
+        # system and can be affected via Linux commands (chmod, chown) under Windows.
+        \cp "${INVENTORY}" ~/.cikit-inventory
+        \chmod a-x ~/.cikit-inventory
+        PARAMS+=" -i ~/.cikit-inventory"
+      fi
+    fi
+  # The "uname -o" cannot be used due to "-o" option is not supported on OS X.
+  elif [[ "$(\uname -s)" =~ "CYGWIN" ]]; then
+    ANSIBLE_INVENTORY=$(\cygpath "${ANSIBLE_INVENTORY}")
+  fi
+
+  if [ -n "${VARS}" ]; then
+    PARAMS+=" -e '{${VARS}}'"
+  fi
+
+  PARAMS+=" -e __targetdir__='${TARGET_DIR}'"
 fi
 
-if [ -n "${VARS}" ]; then
-  PARAMS+=" -e '{${VARS}}'"
+if ${LOCALHOST}; then
+  PARAMS+=" -i 'localhost,'"
 fi
-
-PARAMS+=" -e __targetdir__='${TARGET_DIR}'"
 
 # https://github.com/sclorg/s2i-python-container/pull/169
 export PYTHONUNBUFFERED=1
